import type{ CredentialFrontend } from "@chomp/shared";

export const INITIAL_CREDENTIALS: CredentialFrontend[] = [
  {
    id: "1",
    name: "Google",
    username: "user@gmail.com",
    password: "gO0gLe_S3cr3t_p@ss_991",
    group: "Personal",
    strength: "Strong",
    websiteUrl: "https://google.com",
    notes: "Primary Gmail account for personal use.",
    lastUpdated: "2026-05-15",
    isFavorite: true,
  },
  {
    id: "2",
    name: "Netflix",
    username: "family@domain.com",
    password: "N3tfl1x_and_Chill_2026!",
    group: "Personal",
    strength: "Strong",
    websiteUrl: "https://netflix.com",
    notes: "Family television sharing account.",
    lastUpdated: "2026-04-01",
    isFavorite: true,
  },
  {
    id: "3",
    name: "Bank Vault",
    username: "Main Checking",
    password: "Chomp_M0ney_Gu@rd_88!",
    group: "Finance",
    strength: "Strong",
    websiteUrl: "https://chase.com",
    notes: "Primary checkings and savings portal.",
    lastUpdated: "2026-06-12",
    isFavorite: true,
  },
  {
    id: "4",
    name: "Amazon",
    username: "buyer@email.com",
    password: "Sh0pp1ng_Spree_Amzn_!",
    group: "Personal",
    strength: "Strong",
    websiteUrl: "https://amazon.com",
    notes: "Store credentials and shipping info.",
    lastUpdated: "2026-03-30",
  },
  {
    id: "5",
    name: "Github",
    username: "dev_monster",
    password: "G1t_Ch0mp_v@ult_c@ve_9922",
    group: "Work",
    strength: "Strong",
    websiteUrl: "https://github.com",
    notes: "Developer hub for open-source and stone-slab code.",
    lastUpdated: "2026-06-05",
  },
  {
    id: "6",
    name: "Reddit",
    username: "anon_dino",
    password: "reddit123",
    group: "Social",
    strength: "Weak",
    websiteUrl: "https://reddit.com",
    notes: "Chili discussions and fun memes.",
    lastUpdated: "2026-01-14",
  },
  {
    id: "7",
    name: "Slack Workspace",
    username: "monster@workplace.com",
    password: "Sl@ck_Monster_Work_1",
    group: "Work",
    strength: "Medium",
    websiteUrl: "https://slack.com",
    notes: "Team collaboration and workspace communications.",
    lastUpdated: "2026-05-20",
  },
  {
    id: "8",
    name: "Coinbase",
    username: "crypto_caveman",
    password: "B1t_C01n_t0_the_M00n_99!",
    group: "Finance",
    strength: "Strong",
    websiteUrl: "https://coinbase.com",
    notes: "Crypto wallet and assets.",
    lastUpdated: "2026-06-14",
  },
  {
    id: "9",
    name: "Twitter (X)",
    username: "@rocky_chomper",
    password: "pass",
    group: "Social",
    strength: "Weak",
    websiteUrl: "https://x.com",
    notes: "Social feed.",
    lastUpdated: "2026-02-18",
  },
];

export const GROUP_ICONS = {
  Personal: "user",
  Work: "briefcase",
  Social: "share2",
  Finance: "credit-card",
};
